version: '3.1'

services:
  db:
    image: mysql:8.0 #image 
    container_name: db #name
    restart: unless-stopped 
    env_file: .env #files where we take info
    environment:
      - MYSQL_DATABASE=wordpress #name of base
    volumes:
      - dbdata:/var/lib/mysql #associated volume with local. /usr/bin/docker/volumes as i remember
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network #add to network

  wordpress:
    depends_on:
      - db #start after db
    image: wordpress:5.1.1-fpm-alpine #image
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment: #it s take from .env file
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes: #usr/bin/docker/volumes/wordpress_wordpress (as i remember)
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports: #from local to ":" docker
      - "80:80"
      - "443:443"  
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d #download from local storage to container nginx config
      - certbot-etc:/etc/letsencrypt #storage of ssl
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email Lagutka_98@mail.ru --agree-tos --no-eff-email --force-renewal -d www.altezza34.space -d altezza34.space

volumes:
  certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
